@baseUrl = http://localhost:3003
#@baseUrl = https://part3-caiv.onrender.com
###Get all blogs
GET {{baseUrl}}/api/blogs/



@id = 66bbd2a6a231bf96fe4eed7a
###Get a specific person
GET {{baseUrl}}/api/blogs/{{id}}



###Delete a specific person
DELETE {{baseUrl}}/api/blogs/{{id}}



###Create a new blog
POST {{baseUrl}}/api/blogs
Content-Type: application/json

{
  "title": "Google Blogs",
  "author": "Google",
  "url": "https://blog.google/products/search/",
  "likes": 80
}



###Update
PUT {{baseUrl}}/api/blogs/{{id}}
Content-Type: application/json

{
  "title": "Stack Overflow",
  "author": "Stack Community",
  "url": "https://stackoverflow.blog/",
  "likes": 90
}



@baseUrl = http://localhost:3003
#@baseUrl = https://part3-caiv.onrender.com
###Get all users
GET {{baseUrl}}/api/users/



###Create a new person
POST {{baseUrl}}/api/users
Content-Type: application/json

{
      "username": "leon",
      "name": "leon",
      "password" : "leon"
}



###Login
POST {{baseUrl}}/api/login
Content-Type: application/json

{
      "username": "leon",
      "password" : "leon"
}



###Create a new blog - with logged in user
POST {{baseUrl}}/api/blogs
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imxlb24iLCJpZCI6IjY2YzhmMTU5MmI3MGU2ZTY2OTMxNTljMiIsImlhdCI6MTcyNDQ0ODY4Mn0.aI4PIVas7K_zKsOYOmm2oKMa3ZcrvGpqdiNmsQiQYmI

{
  "title": "Leon Blogs",
  "author": "Leon",
  "url": "https://leonblogs.com//",
  "likes": 1000
}

