@baseUrl = http://localhost:3003
#@baseUrl = https://part3-caiv.onrender.com
###Get all blogs
GET {{baseUrl}}/api/blogs/



@id = 66bbd2a6a231bf96fe4eed7a
###Get a specific person
GET {{baseUrl}}/api/blogs/{{id}}



###Delete a specific person
DELETE {{baseUrl}}/api/blogs/{{id}}



###Create a new person
POST {{baseUrl}}/api/blogs
Content-Type: application/json

{
  "title": "DEV",
  "author": "DEV Community",
  "url": "https://dev.to/",
  "likes": 80
}



###Update
PUT {{baseUrl}}/api/blogs/{{id}}
Content-Type: application/json

{
  "title": "Stack Overflow",
  "author": "Stack Community",
  "url": "https://stackoverflow.blog/",
  "likes": 90
}


